apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-erlang-cluster
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: k8s-erlang-cluster
        image: localhost:5005/k8s_erlang_cluster:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 39135
        env:
        - name: ERL_DIST_PORT
          value: "39135"
        - name: POD_IP
          valueFrom:
            fieldRef:
                fieldPath: status.podIP
