apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-erlang-cluster

resources:
- deployment.yaml
- service.yaml
- namespace.yaml

labels:
- includeSelectors: true
  pairs:
    deployment: k8s-erlang-cluster
